[package]
name = "yarn-webpack"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
actix-web = "4.0"
actix-web-static-files = "4.0"
static-files = "0.2.1"

[build-dependencies]
static-files = "0.2.1"