name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: dtolnay/rust-toolchain@1.85.1
    - name: Remove config.toml
      run: rm .cargo/config.toml
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: Run packaging
      run: cargo package
